/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NftMarketInfo {
  /**
   * data of this nft
   */
  data?: {
    /**
     * Address of creator this nft.
     */
    creator: string;
    /**
     * url with metadata of this nft
     */
    metadata: string;
    /**
     * Price of nft to first sell.
     */
    price: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
